<a href="https://colab.research.google.com/github/War-Eagl/twyptids/blob/master/twyptids_clipasso.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install transformers
!pip install diffusers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 4.7 MB 30.4 MB/s 
     |████████████████████████████████| 120 kB 74.9 MB/s 
     |████████████████████████████████| 6.6 MB 58.3 MB/s 
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 112 kB 23.2 MB/s 


In [2]:
!huggingface-cli login


        _|    _|  _|    _|    _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|_|_|_|    _|_|      _|_|_|  _|_|_|_|
        _|    _|  _|    _|  _|        _|          _|    _|_|    _|  _|            _|        _|    _|  _|        _|
        _|_|_|_|  _|    _|  _|  _|_|  _|  _|_|    _|    _|  _|  _|  _|  _|_|      _|_|_|    _|_|_|_|  _|        _|_|_|
        _|    _|  _|    _|  _|    _|  _|    _|    _|    _|    _|_|  _|    _|      _|        _|    _|  _|        _|
        _|    _|    _|_|      _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|        _|    _|    _|_|_|  _|_|_|_|

        To login, `huggingface_hub` now requires a token generated from https://huggingface.co/settings/tokens .
        
Token: 
Login successful
Your token has been saved to /root/.huggingface/token
Authenticated through git-credential store but this isn't the helper defined on your machine.
You might have to re-authenticate when pushing to the Hugging Face Hub. Run the following command in your termin

In [3]:
!pip install svgwrite
!pip install svgpathtools
!pip install cssutils
!pip install numba
!pip install torch-tools
!pip install visdom
!pip install ftfy
!pip install git+https://github.com/openai/CLIP.git --no-deps

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 67 kB 6.0 MB/s 
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 67 kB 5.9 MB/s 
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 399 kB 32.4 MB/s 
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 43 kB 1.8 MB/s 
     |████████████████████████████████| 676 kB 60.9 MB/s 
     |████████████████████████████████| 46 kB 4.5 MB/s 
     |████████████████████████████████| 26.9 MB 77.2 MB/s 
     |████████████████████████████████| 86 kB 5.1 MB/s 
     |████████████████████████████████| 55 kB 4.1 

In [5]:
!git clone https://github.com/War-Eagl/twyptids
%cd twyptids
!git submodule update --init --recursive
%cd diffvg

data = []
with open("CMakeLists.txt", "r+") as inFile:
    for line in inFile:
        if "find_package(TensorFlow)" in line:
            pass
        else:
            data.append(line)
    inFile.seek(0)
    for d in data:
        inFile.write(d)
    inFile.truncate()
!python setup.py install

%cd ..

Cloning into 'twyptids'...
remote: Enumerating objects: 278, done.
remote: Counting objects: 100% (278/278), done.
remote: Compressing objects: 100% (267/267), done.
remote: Total 278 (delta 13), reused 261 (delta 4), pack-reused 0
Receiving objects: 100% (278/278), 6.94 MiB | 7.71 MiB/s, done.
Resolving deltas: 100% (13/13), done.
/content/twyptids/twyptids
Submodule 'diffvg' (https://github.com/BachiLi/diffvg.git) registered for path 'diffvg'
Cloning into '/content/twyptids/twyptids/diffvg'...
Submodule path 'diffvg': checked out 'e5955dbdcb4715ff3fc6cd7d74848a3aad87ec99'
Submodule 'pybind11' (https://github.com/pybind/pybind11.git) registered for path 'diffvg/pybind11'
Submodule 'thrust' (https://github.com/thrust/thrust.git) registered for path 'diffvg/thrust'
Cloning into '/content/twyptids/twyptids/diffvg/pybind11'...
Cloning into '/content/twyptids/twyptids/diffvg/thrust'...
Submodule path 'diffvg/pybind11': checked out '72b06b86b3824781f31c790dfce67e26e6307816'
Submodule 'tools

In [10]:
!git clone https://github.com/yael-vinker/CLIPasso.git

Cloning into 'CLIPasso'...
remote: Enumerating objects: 386, done.
remote: Total 386 (delta 0), reused 0 (delta 0), pack-reused 386
Receiving objects: 100% (386/386), 12.90 MiB | 17.45 MiB/s, done.
Resolving deltas: 100% (192/192), done.


In [ ]:
%cd CLIPasso

!pip install -r requirements.txt

%cd ..

/content/twyptids/CLIPasso
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 64 kB 3.3 MB/s 
     |████████████████████████████████| 404 kB 54.0 MB/s 
     |████████████████████████████████| 26.9 MB 1.5 MB/s 
     |████████████████████████████████| 122 kB 72.2 MB/s 
     |████████████████████████████████| 786 kB 60.8 MB/s 
     |████████████████████████████████| 56 kB 5.4 MB/s 
     |████████████████████████████████| 82 kB 1.5 MB/s 
     |████████████████████████████████| 392 kB 74.6 MB/s 
     |████████████████████████████████| 8.6 MB 25.0 MB/s 
     |████████████████████████████████| 55 kB 4.2 MB/s 
     |████████████████████████████████| 10.3 MB 32.5 MB/s 
     |████████████████████████████████| 388 kB 72.7 MB/s 
     |████████████████████████████████| 9.9 MB 23.6 MB/s 
     |████████████████████████████████| 3.4 MB 62.5 MB/s 
     |████████████████████████████████| 15.3 MB 260 kB/s 
     |█████

In [ ]:
ORIGINAL_IMAGES_PATH = '/content/twyptids/CLIPasso/target_images/'
ORIGINAL_SKETCHES_PATH = '/content/twyptids/original_sketches/'
MODIFIED_SKETCHES_PATH = '/content/twyptids/images/'

# Generating natural images using stable diffusion

In [ ]:
#@title Enter the initial prompt

from torch import autocast
from diffusers import StableDiffusionPipeline


prompt = "Three headed dragon" #@param {type:"string"}

original_image_filename =  prompt+'.png'



pipe = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", use_auth_token=True)
pipe = pipe.to("cuda")

with autocast("cuda"):
    image = pipe(prompt)["sample"][0]  


image.save(ORIGINAL_IMAGES_PATH + prompt + '.png')

0it [00:00, ?it/s]

In [ ]:
image.save(ORIGINAL_IMAGES_PATH + prompt + '.png')

#Converting natural image to sketch

In [ ]:
%cd /content/twyptids

/content/twyptids


In [ ]:
original_image_filename

'Three headed dragon.png'

In [ ]:
%cd CLIPasso

!python run_object_sketching.py --target_file "$original_image_filename" --mask 1

%cd ..

/content/twyptids/CLIPasso
  0% 0/2001 [00:00<?, ?it/s]/content/twyptids


# Modifying Sketch

In [3]:
%cd twyptids

/content/twyptids


In [6]:
!python modify_sketch.py "/content/twyptids/original_sketches/horse.svg" "add a harness on back of the horse"

/usr/local/lib/python3.7/dist-packages/torchvision/transforms/transforms.py:333: UserWarning: Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. Please use InterpolationMode enum.
  "Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. "
/content/twyptids/original_sketches/horse.svg
add a harness on back of the horse
torch.Size([3, 224, 224])
tensor([[0.6429, 0.6071],
        [0.9330, 0.9911],
        [0.5179, 0.7500],
        [0.4554, 0.7857]])
1
tensor([2], dtype=torch.int32)
tensor([[0.0536, 0.1027],
        [0.6429, 0.7857],
        [0.2277, 0.1027],
        [0.7455, 0.3036],
        [0.5804, 0.0000],
        [0.7768, 0.1161],
        [0.9643, 0.7946],
        [0.2455, 0.2545],
        [0.5268, 0.9687],
        [0.3973, 0.4196]])
3
tensor([2, 2, 2], dtype=torch.int32)
tensor([[0.5446, 0.7723],
        [0.6786, 0.2277],
        [0.9196, 0.5491],
        [0.1027, 0.4643]])
1
tensor([2], dtype=torch.int32)
t

In [8]:
!python modify_sketch.py "/content/twyptids/original_sketches/horse.svg" "make the tail longer"

/usr/local/lib/python3.7/dist-packages/torchvision/transforms/transforms.py:333: UserWarning: Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. Please use InterpolationMode enum.
  "Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. "
/content/twyptids/original_sketches/horse.svg
make the tail longer
torch.Size([3, 224, 224])
torch.Size([3, 224, 224])


In [9]:
!python modify_sketch.py "/content/twyptids/original_sketches/horse.svg" "make the tail curl"

/usr/local/lib/python3.7/dist-packages/torchvision/transforms/transforms.py:333: UserWarning: Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. Please use InterpolationMode enum.
  "Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. "
/content/twyptids/original_sketches/horse.svg
make the tail curl
torch.Size([3, 224, 224])
torch.Size([3, 224, 224])
